version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mfahadwaqar/carprice-a3:${tag:-latest}
    command: python app/main.py
    environment:
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - "8050:80"