name: Build-Test

run-name: ${{ github.actor }} Building and Testing

on:
  push:
    tags:
      - 'v*'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          envkey_APP_MODEL_NAME: ${{ secrets.APP_MODEL_NAME }}
          file_name: .env
          fail_on_empty: true
          sort_keys: true

      - name: Build Docker image
        run: docker compose build

      - name: Run containers
        run: docker compose up -d

      - name: Run Pytest
        run: docker compose exec app pytest test_model.py -v

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mfahadwaqar/carprice-a3
          tags: type=semver,pattern={{raw}}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    environment: Production
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on Remote VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          proxy_host: ${{ vars.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_key: ${{ secrets.KEY }}
          proxy_passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd st125981
            export tag=${{ github.ref_name }}
            docker compose down
            docker compose up -d