name: ML Model CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  # Job 1: Basic Python tests
  basic-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python -m pytest test_model.py -v --tb=short

  # Job 2: Docker build and test
  docker-tests:
    runs-on: ubuntu-latest
    needs: basic-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ml-model-test:latest .

      - name: Run container tests
        run: docker run --rm ml-model-test:latest python -m pytest test_model.py -v

  # Job 3: MLflow connectivity test
  mlflow-tests:
    runs-on: ubuntu-latest
    needs: basic-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install mlflow pandas numpy scikit-learn

      - name: Test MLflow connection
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          python - <<'EOF'
          import mlflow, os
          mlflow.set_tracking_uri(os.getenv("MLFLOW_TRACKING_URI"))
          try:
              exps = mlflow.search_experiments()
              print(f"Connected to MLflow ({len(exps)} experiments found)")
          except Exception as e:
              print("MLflow connection failed:", e)
              exit(1)
          EOF

  # Job 4: Deploy Docker image to Docker Hub
  deploy-docker:
    runs-on: ubuntu-latest
    needs: [basic-tests, docker-tests]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/carprice-a3:latest

  # Job 5: Deploy on remote server (AIT host)
  deploy-server:
    needs: deploy-docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          proxy_host: ${{ vars.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_key: ${{ secrets.KEY }}
          proxy_passphrase: ${{ secrets.PASSPHRASE }}
          source: "docker-compose.yaml"
          target: "st125981/"
          strip_components: 0

      - name: SSH into remote server and redeploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          proxy_host: ${{ vars.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_key: ${{ secrets.KEY }}
          proxy_passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            set -euxo pipefail
            cd st125981
            echo "Pulling latest image and restarting containers..."
            docker compose down || true
            docker compose pull
            docker compose up -d --build
